#ifndef GUESSING_RANDOM_NUMBER_H
#define GUESSING_RANDOM_NUMBER_H

void run_guessing_random_number_game(remaining_numbers_not_guessed, Number_of_attempts_allowed, Number_of_terms_of_vector_v);

#endif
