CPP = g++
FLAGS = -pedantic-errors -std=c++11

main: main.o run_game.o
  $(CPP) main.o run_game.o -o main

.PHONY: clean
clean: main.o run_game.o main
  rm *.o
  rm main
  
main.o: main.cpp run_game.h
  $(CPP) $(FLAGS) -c main.cpp
